
export const homeData = [
    {
      id: 1,
      name: "Maula Jutt",
      rating: 4.7,
      time:"2hr : 33mins",
      desc: "The Legend of Maula Jatt is a 2022 Pakistani Punjabi-language action drama film directed and written by Bilal Lashari. The film is an adaptation of the 1979 Lollywood cult classic film Maula Jatt.",
      starring: "Fawad khan , Mahira khan",
      genres: "Action",
      tags: "Action, Adventure",
      cover: "/public/images/maulaJutt.jpg",
      video: "/public/videos/Maula Jatt.mp4",
      date: "13-Oct-2022",
    },
    {
      id: 2,
      name: "Jawani Phir Nai Ane 2",
      rating: 4.6,
      time: "2hr : 45mins",
      desc: "Now settled into married life, Pervez and Sheikh jump at the chance to travel to Turkey with their wives to visit Pervez's well-to-do brother-in-law, Rahat.",
      starring: "Fahad Mustafa , Humayun Saeed",
      genres: "Funny",
      tags: "Funny, Adventure",
      cover: "/public/images/Jawani phr nai ane.jpg",
      video: "/public/videos/Jawani Phir Nahi Ani 2.mp4",
      date: "22-Aug-2018",
    },
    {
      id: 3,
      name: "Happy Bhag Jayegi",
      rating: 4.6,
      time: "2hr : 05mins",
      desc: "Happy, a vibrant Indian girl, elopes on the day of her wedding so that she can marry Guddu, the man she loves. She mistakenly arrives at the home of a Pakistani politician where chaos ensues.",
      starring: "Ali fazal, Jimmy Shergill",
      genres: "Action",
      tags: "Action , Adventure",
      cover: "/public/images/happy bhag jaige.jpg",
      video: "/public/videos/Happy Bhag Jayegi.mp4",
      date: "19-August-2016 "
    },
    {
      id: 4,
      name: "Bol",
      rating: 4.5,
      time: "2hr : 45mins",
      desc: "The patriarch of a religious Muslim family refuses to accept his transgender son, which creates a conflict within the family and ends up tearing them apart.",
      starring: "Atif Aslam, Iman Ali",
      genres: "Action",
      tags: "Action, Adventure",
      cover: "/public/images/bol.jpg",
      video: "/public/videos/bol.mp4",
      date: "24-June-2011",
    },
    ]
    export const upcome = [
      {
        id : 1,
        name: "Aquaman and the Lost Kingdom",
        cover: "/public/images/upcome/aquaman.jpg",
        time: "2hr : 00mins",
        releaseDate: "20-Dec-2023",
      },
      {
        id : 2,
        name: "The Marvels",
        cover: "/public/images/upcome/marvel.jpg",
        time: "2hr : 15mins",
        releaseDate:"10-Nov-2023",
        },
        {
          id : 3,
          name: "Godzilla Minus One",
          cover: "/public/images/upcome/godzilla.jpg",
          time: "2hr : 30mins",
          releaseDate: "1-Nov-2023",
        },
        {
          id: 4,
          name: "Five Nights at Freddy's",
          cover: "/public/images/upcome/five nights at freddy.jpg",
          time: "2hr : 25mins",
          releaseDate: "27-Oct-2023",
        },
    ]
    export const recommended = [
        {
            id : 1,
            name: "Bank Chor",
            rating: 3.4,
            time: "2hr : 30mins",
            desc: "Champak, a bumbling fool, decides to rob a bank with the help of his two inexperienced friends from Delhi. However, their plan goes haywire causing the robbery to turn into a huge mess.",
            starring: "Vivak Oberoi , Rhea Chakraborty",
            genres: "Comedy",
            tags: "Thriller, Comedy",
            cover: "/public/images/recommended/bank chor.jpg",
            video: "/public/videos/Bank Chor.mp4",
            date: "16-JUNE-2017",
        },
        {
            id : 2,
            name: "Fanaa",
            rating: 4.5,
            time: "2hr : 48mins",
            desc: "Against the advice of her friends, Zooni, a visually impaired Kashmiri girl, falls in love with a tourist guide, Rehan. He helps her get her eyesight back but she remains unaware of his true identity.",
            starring: "Amir Khan , Kajol",
            genres: "Drama",
            tags: "Romance, Drama",
            cover: "/public/images/recommended/fanaa.jpg",
            video: "/public/videos/Fanaa.mp4",
            date: "26-May-2006",
        },
        {
            id : 3,
            name: "Kal Ho Na Ho",
            rating: 4.7,
            time: "3hr : 06mins",
            desc: "Naina, a girl living a dreary life, finds a new meaning to her life when she meets Aman. Even though she loves him, Aman claims to be a married man and convinces Rohit, her friend, to woo her.",
            starring: "Shahrukh Khan , Priety",
            genres: "Musical",
            tags: "Romance, Musical",
            cover: "/public/images/recommended/kal ho na ho.jpg",
            video: "/public/videos/Kal Ho Naa Ho.mp4",
            date: "28-Nov-2003",
        },
        {
            id : 4,
            name: "Marjaavaan",
            rating: 4.6,
            time: "2hr : 32mins",
            desc: "Gangster Raghu works for Narayan Anna, the local don, and is his favourite henchman. However, Vishnu, Narayan's son, is jealous of Raghu's popularity with his father and schemes against him.",
            starring: "Sidharth Malhotra",
            genres: "Action",
            tags: "Action, Drama",
            cover: "/public/images/recommended/Marjaavaan.jpg",
            video: "/public/videos/Marjaavaan.mp4",
            date: "15-Nov-2019",
        },
    ]
    export const trending = [

    ]
    export const latest = [
      {
          id : 1,
          name: "Jailer",
          cover: "/public/images/latest/jailer.jpeg",
          time: "2hr : mins",
          date: "10-Aug-2023",
      },
      {
          id : 2,
          name: "Pathan",
          cover: "/public/images/latest/pathan.jpeg",
          time: "2hr : 26mins",
          date: "25-Jan-2023",
      },
      {
          id : 3,
          name: "Bawaal",
          cover: "/public/images/latest/bawaal.jpeg",
          time: "2hr : 17mins",
          date: "21-July-2023",
      },
      {
          id : 4,
          name: "Heart of stone",
          cover: "/public/images/latest/stone of heart.jpeg",
          time: "2hr : 02mins",
          date: "11-Aug-2023",
      },
  ]